name: 'cargo-dependencies'
description: 'Keep track of dependencies and binary size'
author: 'marlonbaeten'
branding:
  icon: 'list'
  color: 'green'
inputs:
  token:
    description: 'Github token to use'
    required: true
  mainBranchName:
    description: 'Pull requests will be compared to a main branch'
    required: false
    default: 'main'
runs:
  using: 'node16'
  main: 'dist/index.js'
